version: "2"
services:
  db:
    image: 3manuek/postgres10
    restart: always
    ports:
      - 5432:5432
    networks:
      clusterpg:
        aliases:
          - db1
    volumes:
      - /opt/pg10/data
    extra_hosts:
      - "dockerhost:192.168.0.10"
  db2:
    image: 3manuek/postgres10
    restart: always
    ports:
      - 5433:5432
    networks:
      clusterpg:
        aliases:
          - db2
    volumes:
      - /opt/pg10/data
    extra_hosts:
      - "dockerhost:192.168.0.10"
#  command: true
volumes:
  data: {} 

networks:
  clusterpg:



#db:
#  image: 3manuek/postgres10
#  volumes_from:
#    - postgres10
#  ports:
#    - "5432:5432"
#  command: true

