postgres10:
  image: 3manuek/postgres10
  restart: always
  volumes:
    - /opt/pg10/data
#  command: true

db:
  image: 3manuek/postgres10
  volumes_from:
    - postgres10
  ports:
    - "5432:5432"

